In [ ]:
class classnames:
    #some functions and variables
    #function -- used to perform the specific activity
    #variables -- Data(memory) 

In [12]:
def test():
    print("test() for function") 
    return
test()

test() for function


In [9]:
class Demo:
    def test(self):
        print("test() for the class and method") 
        return
obj=Demo()
obj.test()

test() for the class and method


In [14]:
class Demo1:
    def fact(self,n):
        # return the factorial
        fact=1
        while(n!=0):
           fact=fact*n
           n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))

120


In [15]:
class Demo2:
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print()
        print()
c1=Demo2()
print(c1.accept(10,20))

SyntaxError: invalid syntax (<ipython-input-15-0a2d9d135600>, line 6)

In [17]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [19]:
import re
sum=0
pattern = 'back'
if re.match(pattern,'backup.txt'):
    sum +=1
if re.match(pattern,'text.back'):
    sum +=2
if re.search(pattern,'backup.txt'):
    sum +=4
if re.search(pattern,'text.back'):
    sum +=8
print(sum)

13


In [22]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [24]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [28]:
#indexing and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [29]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])

first row : [1 2 3]


In [32]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row :",a1[1])

second row : [4 5 6]


In [33]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row:",a1[1,:])

slicing row: [4 5 6]


In [27]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [36]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[3.51011063 3.75497967 5.72960896 5.80250644 5.63868475 4.64269375
 5.01080374 5.7691873  3.06748638 5.09980317]
min value= 3.0674863795992087
max value= 5.802506442239236
mean value= 4.802586478517388
median value= 5.055303456814694


In [38]:
#multiply of 1D arrays
#numpy.dot(x,y)
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [40]:
c1=np.array([1,2],[3,4])
c2=np.array([3,4],[1,2])
np.mutual(c1,c2)

TypeError: data type not understood

b1=np.array([1,5],[6,9])
b2=np.array([2,3],[1,6])
np.mutual(b1,b2)

In [44]:
import numpy as np
a=np.array([1,2,3,5,8])
b=np.array([0,3,4,2,1])
c=a+b
c=c*a
print(c[2])

21


In [46]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"Mobile Number":["999","888","777","888","777","999"],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID Mobile Number Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd


In [47]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID Mobile Number Address
01    Anil    anil@gmail.com           999     Hyd
02   Akhil   akhil@gmail.com           888     Hyd
03  Dinesh  dinesh@gmail.com           777     Hyd
04  Harsha  harsha@gmail.com           888     Hyd
05    Ajay    ajay@gmail.com           777     Hyd
06  Kranth  kranth@gmail.com           999     Hyd
